pre-commit:
  parallel: true
  jobs:
    - name: TypeScript
      group:
        parallel: true
        jobs:
          - name: Workspaces
            run: npx --workspaces tsgo
          - name: Root
            run: npx tsgo
    - name: ESLint
      run: npx eslint --cache --concurrency auto
    - name: editorconfig-checker
      run: npx editorconfig-checker

commit-msg:
  parallel: true
  jobs:
    - name: commitlint
      run: npx commitlint --edit $1

check:
  parallel: true
  jobs:
    - name: TypeScript
      group:
        parallel: true
        jobs:
          - name: Workspaces
            run: npx --workspaces tsgo
          - name: Root
            run: npx tsgo
    - name: ESLint
      run: npx eslint --cache --concurrency auto
    - name: editorconfig-checker
      run: npx editorconfig-checker

fix:
  jobs:
    - name: TypeScript
      group:
        parallel: true
        jobs:
          - name: Workspaces
            run: npx --workspaces tsgo
          - name: Root
            run: npx tsgo
    - name: ESLint
      run: npx eslint --fix --cache --concurrency auto
    - name: editorconfig-checker
      run: npx editorconfig-checker
